services:
  - type: web
    name: user-management-system
    env: static
    buildCommand: npm run build
    staticPublishPath: dist/user-management-system/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html  