buildCommand: npm install && npm run build -- --configuration production
publish: frontend/dist/angular-signup-verification-boilerplate/browser
routes:
  - type: rewrite
    source: /.*
    destination: /index.html
